### ISSUE TITLE
Fix relative paths

### ISSUE THREAD

**Issue by bw4sz** [bw4sz/FutureAnalog#1]
@laurajanegraham 
Here is a quick list i can see of obvious relative paths to change.

AlphaMapping.R 
-  Line 31: I think this can be commented out for the moment, looks like we are really using the dropbox folder for anything besides saving R workspaces. I'll need Anusha to share the folder with you (she was the owner, so i couldn't see it).
- Line 32: To where ever your git repo is.
-  120: This is where the niche models get saved. I'd make this local C: drive and not the github folder, the files can be quite large.

SDM.R
_Line 67: This is where the *current_ climate layers were stored on a hard drive. If you do change which layers, you'll probably need to change the names eventually. Quick googling suggest they can be downloaded here. http://www.worldclim.org/current
- Line 99: This is where the _future_ climate layers were stored on the hard drive. I don't think they need to be hyper fine scaled, but something to think about going forward. http://www.worldclim.org/cmip5_2.5m#com

**Comment by laurajanegraham** [comment]
Thanks for this. At the moment the paths are set as absolute paths, what would make the code more portable would be to set these to relative paths. It would require a few more changes now (but not really that many), but it means that all that anyone running the code needs to do is set their working directory to the location of their local copy of the github repo. Would you mind if I did this? No problems if you'd rather I didn't.

**Comment by bw4sz** [comment]
Hi!

I really want you to feel like this is your project. You are welcome to do anything you like! I'm just here to help.
